apiVersion: v1
kind: ConfigMap
metadata:
  name: wallarm-sidecar-nginx-conf
data:
  default: |
      log_format json_custom escape=json
      '{'
        '"http.url":"$request_uri",'
        '"http.version":"$server_protocol",'
        '"http.status_code":$status,'
        '"http.method":"$request_method",'
        '"http.referer":"$http_referer",'
        '"http.useragent":"$http_user_agent",'
        '"time_local":"$time_local",'
        '"remote_addr":"$remote_addr",'
        '"remote_user":"$remote_user",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"request_time":$request_time,'
        '"response_content_type":"$sent_http_content_type",'
        '"X-Forwarded-For":"$proxy_add_x_forwarded_for",'
        '"wallarm_request_mono_time":$wallarm_request_mono_time,'
        '"wallarm_request_cpu_time":$wallarm_request_cpu_time'
      '}';
      server {
          listen 80 default_server;
          listen [::]:80 default_server ipv6only=on;
          server_name localhost;
          access_log /var/log/nginx/access.log json_custom;
          root /usr/share/nginx/html;
          index index.html index.htm;
          wallarm_mode {{ .Values.wallarm.mode | quote }};
          # wallarm_instance 1;
          set_real_ip_from 0.0.0.0/0;
          real_ip_header X-Forwarded-For;
          location / {
                  proxy_pass http://localhost:{{ .Values.wallarm.app_container_port }};
                  include proxy_params;
          }
      }
